export const IMPORT_STATUS = {
     IN_PROGRESS: "IN_PROGRESS",
     ERROR: "ERROR",
     SUCCESS: "SUCCESS",
};


export const IMPORT_TYPE = {
     ADD_NUMBERS: "ADD_NUMBERS",
     DELETE_NUMBERS: "DELETE_NUMBERS",
     ADD_RESULTS: "ADD_RESULTS",
     DELETE_RESULTS: "DELETE_RESULTS",
     ADD_GUESTS: "ADD_GUESTS",
     DELETE_GUESTS: "DELETE_GUESTS",
};
